---
- hosts: [ml-compute-engine]
  become: yes
- ansible.builtin.import_playbook: install_necessary_package.ansible.yaml
- ansible.builtin.import_playbook: synchronize_code.ansible.yaml
- ansible.builtin.import_playbook: set_up_python_venv.ansible.yaml
