---
- hosts: ml-compute-engine
  become: yes
  gather_facts: no
  tasks: 
    - name: Create the virtual environment 
      ansible.builtin.pip:
        requirements: /opt/Thesis/Code/requirements.txt
        virtualenv: /home/nguyenquangminh/venv
        virtualenv_python: python3
        extra_args: --no-cache-dir
