---
- hosts: ml-compute-engine
  become: yes
  gather_facts: no
  name: Synchronize code
  tasks:
    - name: Pulling code from github
      ansible.builtin.git:
        repo: https://github.com/NguyenQuangMinh0504/Python-SYN-Flood-Attack-Tool
        dest: /opt/SynFlood
        update: yes
        clone: yes
        force: yes
  
    - name: Install necessary package
      ansible.builtin.apt:
        name:
          - python3-scapy
  
    - name: Create the virtual environment 
      ansible.builtin.pip:
        name:
          - scapy
        virtualenv: /home/nguyenquangminh/syn_flood/venv
        virtualenv_python: python3
        extra_args: --no-cache-dir



  